# Generated by Django 5.0.6 on 2026-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('quota_warning', 'Quota Warning'), ('blocked', 'Blocked'), ('injection_blocked', 'Injection Blocked'), ('ip_blocked', 'IP Blocked'), ('rate_limited', 'Rate Limited')], max_length=50),
        ),
    ]
