# Generated by Django 5.0.6 on 2026-07-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='teams.team')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Log',
                'verbose_name_plural': 'Usage Logs',
                'db_table': 'usage_logs',
                'indexes': [models.Index(fields=['team', 'created_at'], name='usage_logs_team_id_26e78b_idx'), models.Index(fields=['user', 'created_at'], name='usage_logs_user_id_dcf91c_idx'), models.Index(fields=['provider_name', 'created_at'], name='usage_logs_provide_40cb36_idx')],
            },
        ),
    ]
