# Generated by Django 5.0.6 on 2026-07-24 15:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('budget', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('limit', models.DecimalField(decimal_places=4, default=Decimal('10.0000'), max_digits=12)),
                ('spent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('selected_model', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team Provider',
                'verbose_name_plural': 'Team Providers',
                'db_table': 'team_providers',
                'unique_together': {('team', 'name')},
            },
        ),
    ]
