# Generated by Django 5.0.6 on 2026-07-24 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisioningTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('figma_transfer_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('task_type', models.CharField(choices=[('onboard', 'Onboard'), ('offboard', 'Offboard')], max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('steps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provisioning Task',
                'verbose_name_plural': 'Provisioning Tasks',
                'db_table': 'provisioning_tasks',
            },
        ),
    ]
